name: Build KernelSU Next SUSFS All
on:
  workflow_dispatch:
    inputs:
      CPU:
        type: choice
        description: "Branch"
        required: true
        default: sm8650
        options:
          - sm7550
          - sm7675
          - sm8450
          - sm8475
          - sm8550
          - sm8650
          - sm8750
      FEIL:
        type: choice
        description: "Configuration File"
        required: true
        default: oneplus_13r
        options:
          - oneplus_nord_ce4_v
          - oneplus_ace_3v_v
          - oneplus_nord_4_v
          - oneplus_10_pro_v
          - oneplus_10t_v
          - oneplus_11r_v
          - oneplus_ace2_v
          - oneplus_ace_pro_v
          - oneplus_11_v
          - oneplus_11_t
          - oneplus_12r_v
          - oneplus_ace2pro_v
          - oneplus_ace3_v
          - oneplus_open_v
          - oneplus12_v
          - oneplus_13r
          - oneplus_ace3_pro_v
          - oneplus_ace5
          - oneplus_pad2_v
          - oneplus_13
          - oneplus_ace5_pro
          - oneplus_13t
          - bug in GitHub
      CPUD:
        type: choice
        description: "Processor Codename"
        required: true
        default: pineapple
        options:
          - crow
          - waipio
          - kalama
          - pineapple
          - sun
      ANDROID_VERSION:
        type: choice
        description: "Kernel Android Version"
        required: true
        default: android14
        options:
          - android12
          - android13
          - android14
          - android15
      KERNEL_VERSION:
        type: choice
        description: "Kernel Version"
        required: true
        default: "6.1"
        options:
          - "5.10"
          - "5.15"
          - "6.1"
          - "6.6"
      BUILD_METHOD:
        type: choice
        description: "Build Method"
        required: true
        default: gki
        options:
          - gki
          - perf
      KSUNEXT_ENABLED:
        description: "Add KSU Next"
        required: true
        type: boolean
        default: true
      SUSFS_ENABLED:
        description: "Add SUSFS"
        required: true
        type: boolean
        default: true
      SUSFS_CI:
        description: "Does the SUSFS module download use CI?"
        required: true
        type: boolean
        default: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Existing steps remain unchanged until LTO configuration

      - name: Enforce LTO Thin configuration
        run: |
          cd kernel_workspace/kernel_platform
          # Force ThinLTO in all build configurations
          find . -name "build.config*" -exec sed -i \
            -e 's/LTO=full/LTO=thin/g' \
            -e 's/LTO=none/LTO=thin/g' \
            -e 's/^LTO=.*/LTO=thin/g' {} \;
          
          # Ensure ThinLTO flags
          if ! grep -q "LTO=thin" common/build.config.gki; then
            echo -e "\n# ThinLTO Configuration\nLTO=thin" >> common/build.config.gki
          fi
          
          # Verify configuration
          echo "Current LTO configuration:"
          grep "LTO=" common/build.config.gki || true

      - name: Build kernel (ThinLTO Optimized)
        if: ${{ github.event.inputs.CPU == 'sm8650' || github.event.inputs.CPU == 'sm7675' }}
        run: |
          cd kernel_workspace
          export THINLTO_NAME_SUFFIX="-ThinLTO"
          LTO=thin ./kernel_platform/build_with_bazel.py -t ${{ github.event.inputs.CPUD }} ${{ github.event.inputs.BUILD_METHOD }}

      # Modified artifact naming with ThinLTO markers
      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3_ThinLTO_KernelSU_Next_${{ env.KSUVER }}_${{ steps.feil_clean.outputs.value }}
          path: ./AnyKernel3/*
