name: Build KernelSU Next SUSFS All (ThinLTO)

on:
  workflow_dispatch:
    inputs:
      CPU:
        type: choice
        description: "SoC Platform Branch"
        required: true
        default: sm8650
        options:
          - sm7550
          - sm7675
          - sm8450
          - sm8475
          - sm8550
          - sm8650
          - sm8750
      FEIL:
        type: choice
        description: "Device Configuration Profile"
        required: true
        default: oneplus_13r
        options:
          - oneplus_nord_ce4_v
          - oneplus_ace_3v_v
          - oneplus_nord_4_v
          - oneplus_10_pro_v
          - oneplus_10t_v
          - oneplus_11r_v
          - oneplus_ace2_v
          - oneplus_ace_pro_v
          - oneplus_11_v
          - oneplus_11_t
          - oneplus_12r_v
          - oneplus_ace2pro_v
          - oneplus_ace3_v
          - oneplus_open_v
          - oneplus12_v
          - oneplus_13r
          - oneplus_ace3_pro_v
          - oneplus_ace5
          - oneplus_pad2_v
          - oneplus_13
          - oneplus_ace5_pro
          - oneplus_13t
          - bug in GitHub
      CPUD:
        type: choice
        description: "Device Codename"
        required: true
        default: pineapple
        options:
          - crow
          - waipio
          - kalama
          - pineapple
          - sun
      ANDROID_VERSION:
        type: choice
        description: "Android Base Version"
        required: true
        default: android14
        options:
          - android12
          - android13
          - android14
          - android15
      KERNEL_VERSION:
        type: choice
        description: "Linux Kernel Version"
        required: true
        default: "6.1"
        options:
          - "5.10"
          - "5.15"
          - "6.1"
          - "6.6"
      BUILD_METHOD:
        type: choice
        description: "Build Type Selection"
        required: true
        default: gki
        options:
          - gki
          - perf
      KSUNEXT_ENABLED:
        description: "Enable KernelSU Next Integration"
        required: true
        type: boolean
        default: true
      SUSFS_ENABLED:
        description: "Enable SUSFS Filesystem Enhancements"
        required: true
        type: boolean
        default: true
      SUSFS_CI:
        description: "Use CI-built SUSFS Modules"
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      THINLTO_MARKER: "-ThinLTO"
      KSU_MODULE_VERSION: "1.5.2+"

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 16384
          temp-reserve-mb: 8192
          swap-size-mb: 16384
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Configure Git Identity
        run: |
          git config --global user.name "KernelCI-Bot"
          git config --global user.email "kernel-ci@android.com"
          git config --global init.defaultBranch main

      - name: Install Build Essentials
        run: |
          sudo apt-get update && sudo apt-get full-upgrade -y
          sudo apt-get install -y \
            jq python3-dev python3-pip \
            git-lfs curl patchelf \
            bc bison flex libssl-dev \
            libncurses-dev libelf-dev

      - name: Validate Input Parameters
        run: |
          echo "Selected Configuration:"
          echo "SoC: ${{ github.event.inputs.CPU }}"
          echo "Device Profile: ${{ github.event.inputs.FEIL }}"
          echo "Codename: ${{ github.event.inputs.CPUD }}"
          echo "Android: ${{ github.event.inputs.ANDROID_VERSION }}"
          echo "Kernel: ${{ github.event.inputs.KERNEL_VERSION }}"
          echo "Build Method: ${{ github.event.inputs.BUILD_METHOD }}"
          echo "SUSFS Source: ${{ github.event.inputs.SUSFS_CI && 'CI' || 'Release' }}"

      - name: Initialize Repository
        run: |
          mkdir -p kernel_workspace
          cd kernel_workspace
          repo init -u https://github.com/OnePlusOSS/kernel_manifest.git \
            -b refs/heads/oneplus/${{ github.event.inputs.CPU }} \
            -m ${{ github.event.inputs.FEIL }}.xml \
            --depth=1 \
            --repo-rev=stable
          repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle
          repo forall -c 'git lfs pull'

      - name: Apply Version Sanitization
        run: |
          cd kernel_workspace/kernel_platform
          find . -name setlocalversion -exec sed -i \
            -e 's/ -dirty//g' \
            -e '/res=.*/a res=${res//-dirty/}' {} \;
          git commit -am "Sanitize kernel version strings" || true

      - name: Enforce ThinLTO Configuration
        run: |
          cd kernel_workspace/kernel_platform
          # Force ThinLTO in all build configurations
          find . -name "build.config*" -exec sed -i \
            -e 's/LTO=full/LTO=thin/g' \
            -e 's/LTO=none/LTO=thin/g' \
            -e '/^LTO=/d' \
            -e '/include/a LTO=thin' {} \;
          
          # Verify LTO configuration
          echo "Final LTO Configuration:"
          grep -r "LTO=" --include="build.config*" .

      - name: Integrate KernelSU Next
        if: ${{ github.event.inputs.KSUNEXT_ENABLED }}
        run: |
          cd kernel_workspace/kernel_platform
          curl -fsSL "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | \
            bash -s -- --branch next --lto thin
          
          cd KernelSU-Next
          KSU_COMMITS=$(git rev-list --count HEAD || echo 10200)
          echo "KSU_VERSION=$((KSU_COMMITS + 10200))" >> $
